# $schema: "./schema.json"
links:
  github:
    repo: github.com/jhockert/resume
    link: https://github.com/jhockert/resume
    releases: https://github.com/jhockert/resume/releases
  page:
    name: jhockert.github.io/resume
    link: https://jhockert.github.io/resume
name: Jonas Höckert
description: >-
 IT professional with solid experience in technical support, consulting, and DevOps.
 Committed to delivering high-quality service and constantly improving processes to boost efficiency.
 Started experimenting with computers and various technologies as a hobby from an early age,
 now applying that curiosity and practical knowledge in a professional setting. 
 Motivated to keep learning and growing—both technically, by deepening skills in programming and cloud services,
 and personally, by strengthening communication and teamwork to contribute effectively in group environments
contact:
  email: jonas@jhockert.se
  location: "Sundbyberg, Stockholm"
experience:
  - title: IT Consultant - DevOps
    company: Nexer Infrastructure & Brickstone AB
    period: "2022 - present"
    description: >-
      Full time consultant for Saab AB first with Nexer Infrastructure and later Brickstone AB.
      Responsibilities included developing and maintaining internal tools for the development environment, managing CI/CD pipelines, and providing user support to developers.
    responsibilities:
      - Developed CLI tools and built Docker containers including automation of releases
      - Configuration as code using ansible
      - Scripting using Go, bash and python
      - Automation using jenkins for CI/CD pipelines with scripted pipeline framework
      - Working with 9LV software platform
      - Knowledge sharing by documentation and presentations
      - Technical advisor as part of internal office relocation project
    achievments:
      - Rewrote ansible code to fully maintain build environment infrastructure with configuration as code
      - Automated agent bootstrapping using generic image accelerating build environment deployment
      - Set up load balanced and fully encrypted on-prem visualisation service cluster including opensearch, grafana and others
      - Set up on-prem kubernetes cluster based on k3s using ansible and ArgoCD
    technologies:
      - Ansible
      - Jenkins
      - Grafana
      - Go
      - Python
      - docker
      - Bash
      - VMware
      - K3s
      - Linux

  - title: IT Support Technician
    company: Wallenstam
    period: "2019 - 2022"
    description: |
      Delivered technical support within Wallenstam's internal IT organization. Responsibilities included troubleshooting issues, packaging for SCCM/MECM, and providing technical guidance.
    responsibilities:
      - Provided user support and resolved technical issues
      - Management and troubleshooting of servers, networks, applications and firewalls
      - Planning and execution for relocation of server room
      - Set up networking for edge sites
      - Served as the system owner for the ticketing system Easit
      - Facilitating large scale meetings
    technologies:
      - SCCM/MECM
      - Juniper
      - Active Directory
      - Exchange On-Prem
      - Office 365
      - Azure AD
      - Checkpoint
      - Microsoft SQL Server
      - Veeam
      - Powershell and PSADT

  - title: IT Consultant
    company: Talangjägarna Consulting AB & Atea Sverige
    period: "2017-2019"
    description: |
      Worked as part of Atea's Onsite Services team, first as a consultant and later on directly hired by Atea. Provided direct support to clients in their daily operations.
    responsibilities:
      - Managed Windows 10 clients and mobile devices
      - Participated in network migration projects, replacing hardware with Cisco Meraki
      - Engaged with suppliers and contributed to internal projects
      - Repaired and managed Point-of-Service systems
      - Offered on-site technical support
      - Administered server and network infrastructure
      - Re-imaging of computers
      - Facilitated large video conferences
      - Printer maintenance and troubleshooting
    achievments:
      - Migrated customer client deployment from Clonezilla to MDT setup accelerating deployment of client computers
    technologies:
      - Windows 7-10
      - Microsoft Server
      - Active Directory
      - Snow MDM
      - Microsoft Deployment Toolkit
      - Cisco Meraki
      - Microsoft Server
      - Windows 10
      - Active Directory
      - Cisco Video Systems
      - Printers

  - title: Service Desk Technician & IT Consultant
    company: Softronic AB
    period: "2012 - 2016"
    description: >-
      Provided support for software, hardware, and operational systems for multiple clients, utilizing various ticketing systems to manage requests.
      On-site support provided for customers as a consultant
    responsibilities:
      - Supported both Mac OSX and Windows environments
      - Server administration and hardware repairs
      - Delivered support via phone and email
      - Assisted with products such as Active Directory, Windows, and Citrix
    achievments: 
      - Led an inventory project for over 1,000 computers and established processes for hardware management
    technologies:
      - Active Directory
      - HPDM
      - SafeCom
      - HP Networking
      - Hardware Repair (Mac and PC)
      - Windows (XP, 7, 8, 10, Server 2003, 2008, 2012)
      - Citrix
      - SAP CDT
      - Microsoft Office (2003, 2004, 2010, 2013)

  - title: Machine operator
    company: Packningsspecialisten
    period: "2011"
    description: |
      Short term work in a factory specializing in gaskets.
    responsibilities:
      - Producing and packaging rubber gaskets

education:
  - institution: IT-Gymnasiet Sundbyberg (High School - Systems Sciences)
    year: "2008-2011"
  - institution: Yoshida Institute of Japanese Language
    year: "2016-2017"
  - institution: "LFS458: Kubernetes Administration"
    year: "2022"

certificates:
  - name: "LFS458: Kubernetes Administration (Participation Certificate)"
    year: "2022"
  - name: "Japanese Language Proficiency Test - N3 Level"
    year: "2017"

languages:
  - Swedish - Native
  - English - Fluent
  - Japanese - Fluent, daily-conversational

personal_projects:
  - area: Networking
    technologies: 
      - Pfsense
      - OPNSense
      - Cisco Meraki
      - Unifi
  - area: Platforms
    technologies: 
      - Linux
      - KVM
      - Docker
      - Kubernetes
  - area: Hosting
    technologies:
      - Nginx
      - Traefik
      - MariaDB
      - Nextcloud
  - area: Development
    technologies:
      - Django
      - Bootstrap
      - PHP
      - HTML
      - CSS
