name: Release on Tag

on:
  push:
    tags:
      - 'v*'  # Triggers on tags that start with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Python script
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - run: python resume_generator.py
       
      - name: Upload PDF to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: resume.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Python script
        run: |
          mkdir http
          mv resume.html http/

      - name: Deploy HTML to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: http 
