name: Release on Tag

on:
  push:
    tags:
      - 'v*'  # Triggers on tags that start with 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python resume_generator.py
       
      - name: Upload PDF to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: resume.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create http folder
        run: |
          mkdir http
          mv resume.html http/

      - name: Deploy HTML to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: http 
