name: Release on Tag

on:
  push:
    tags:
      - 'v*'  # Triggers on tags that start with 'v'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python resume_generator.py

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          files: |
           resume.html
           resume.pdf
       
      - name: Move files
        run: |
          mkdir -p ./public
          mv ./resume.html ./public/
          mv ./static ./public/

      - name: Deploy HTML to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public 
